# Generated by Django 3.2 on 2023-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='expertise',
            field=models.SmallIntegerField(choices=[(0, 'None Specified'), (1, 'Novice'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert'), (6, 'Professional Runner')], default=0, help_text='value to give a coaches experience for users to select against', max_length=2),
        ),
    ]
