# Generated by Django 3.2 on 2023-08-08 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_registration_date_raceregistration_registration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surface', models.SmallIntegerField(choices=[(0, 'Not Specified'), (1, 'Road'), (2, 'Trail'), (3, 'Road/Trail'), (4, 'Track')], default=0, max_length=2)),
                ('description', models.TextField()),
                ('distance_unit', models.SmallIntegerField(choices=[(0, 'Kilometers'), (1, 'Miles')], default=0, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='race',
            name='distance_unit',
        ),
        migrations.AlterField(
            model_name='group',
            name='coached_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coach'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='training_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pacinggroup',
            name='pace_target',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Pacer',
            fields=[
                ('coach_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.coach')),
                ('distance_preferences', models.ManyToManyField(default=None, related_name='type_pacers', to='api.RaceType')),
            ],
            bases=('api.coach',),
        ),
        migrations.AddField(
            model_name='pacinggroup',
            name='pacers',
            field=models.ManyToManyField(blank=True, related_name='pacing_groups', to='api.Pacer'),
        ),
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.racetype'),
        ),
    ]
