# Generated by Django 3.2 on 2023-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coach_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('APPLIED', 'Applied'), ('INACTIVE', 'Inactive')], default='APPLIED', max_length=50),
        ),
    ]
