# Generated by Django 3.2 on 2023-08-09 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230809_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='private_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'None Specified'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=0, max_length=2),
        ),
    ]
