# Generated by Django 3.2 on 2023-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_pacinggroup_pace_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Alabama"),
                    (2, "Alaska"),
                    (3, "Arizona"),
                    (4, "Arkansas"),
                    (5, "California"),
                    (6, "Canal"),
                    (7, "Colorado"),
                    (8, "Connecticut"),
                    (9, "Delaware"),
                    (10, "District"),
                    (11, "Florida"),
                    (12, "Georgia"),
                    (13, "Guam"),
                    (14, "Hawaii"),
                    (15, "Idaho"),
                    (16, "Illinois"),
                    (17, "Indiana"),
                    (18, "Iowa"),
                    (19, "Kansas"),
                    (20, "Kentucky"),
                    (21, "Louisiana"),
                    (22, "Maine"),
                    (23, "Maryland"),
                    (24, "Massachusetts"),
                    (25, "Michigan"),
                    (26, "Minnesota"),
                    (27, "Mississippi"),
                    (28, "Missouri"),
                    (29, "Montana"),
                    (30, "Nebraska"),
                    (31, "Nevada"),
                    (32, "New Hampshire"),
                    (33, "New Jersey"),
                    (34, "New Mexico"),
                    (35, "New York"),
                    (36, "North Carolina"),
                    (37, "North Dakota"),
                    (38, "Ohio"),
                    (39, "Oklahoma"),
                    (40, "Oregon"),
                    (41, "Pennsylvania"),
                    (42, "Puerto Rico"),
                    (43, "Rhode Island"),
                    (44, "South Carolina"),
                    (45, "South Dakota"),
                    (46, "Tennessee"),
                    (47, "Texas"),
                    (48, "Utah"),
                    (49, "Vermont"),
                    (50, "Virgin Islands"),
                    (51, "Virginia"),
                    (52, "Washington"),
                    (53, "West Virginia"),
                    (54, "Wisconsin"),
                    (55, "Wyoming"),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="State",
        ),
        migrations.AlterField(
            model_name="group",
            name="city",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.deletion.SET_DEFAULT,
                related_name="city_races",
                to="api.city",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="race",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.deletion.SET_DEFAULT,
                related_name="race_groups",
                to="api.race",
            ),
        ),
    ]
