# Generated by Django 3.2 on 2023-08-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230809_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'zip_code', 'state')},
        ),
    ]
